import { Router } from 'express';
import authRoutes from './routes/auth.js';
import teamRoutes from './routes/teams.js';
import jobRoutes from './routes/jobs.js';
import leadRoutes from './routes/leads.js';
import verificationRoutes from './routes/verification.js';
import exportRoutes from './routes/exports.js';
import billingRoutes from './routes/billing.js';
import analyticsRoutes from './routes/analytics.js';
import apiKeyRoutes from './routes/apiKeys.js';
import adminRoutes from './routes/admin.js';
import webhookRoutes from './routes/webhooks.js';
import assistantRoutes from './routes/assistant.js';
import integrationsRoutes from './routes/integrations.js';
import searchStatusRoutes from './routes/search-status.js';
import leadListsRoutes from './routes/lead-lists.js';
import companiesRoutes from './routes/companies.js';
import sendingAccountsRoutes from './routes/sending-accounts.js';
import campaignsRoutes from './routes/campaigns.js';
import trackingRoutes from './routes/tracking.js';
import leadImportRoutes from './routes/lead-import.js';
import intelligenceRoutes from './routes/intelligence.js';
import domainHuntRoutes from './routes/domain-hunt.js';

export const apiRouter = Router();

apiRouter.use('/auth', authRoutes);
apiRouter.use('/teams', teamRoutes);
apiRouter.use('/jobs', jobRoutes);
apiRouter.use('/leads', leadRoutes);
apiRouter.use('/verification', verificationRoutes);
apiRouter.use('/exports', exportRoutes);
apiRouter.use('/billing', billingRoutes);
apiRouter.use('/analytics', analyticsRoutes);
apiRouter.use('/api-keys', apiKeyRoutes);
apiRouter.use('/admin', adminRoutes);
apiRouter.use('/webhooks', webhookRoutes);
apiRouter.use('/assistant', assistantRoutes);
apiRouter.use('/integrations', integrationsRoutes);
apiRouter.use('/search', searchStatusRoutes);
apiRouter.use('/lead-lists', leadListsRoutes);
apiRouter.use('/companies', companiesRoutes);
apiRouter.use('/sending-accounts', sendingAccountsRoutes);
apiRouter.use('/campaigns', campaignsRoutes);
apiRouter.use('/track', trackingRoutes);
apiRouter.use('/leads/import', leadImportRoutes);
apiRouter.use('/intelligence', intelligenceRoutes);
apiRouter.use('/domain-hunt', domainHuntRoutes);
